const {test,expect}=require('@playwright/test');
const A='0x1111111111111111111111111111111111111111';
async function fixture(page){
 const state={leverage:5,margin:'cross',funding:'0.0001',unavailable:false,unknown:false,position:'2',orders:[]};const posted=[];
 const meta={universe:[{name:'ETH',szDecimals:4,maxLeverage:20},{name:'BTC',szDecimals:5,maxLeverage:40}]};
 const ctx=()=>({markPx:'21',oraclePx:'20',prevDayPx:'20',dayNtlVlm:'2500000',openInterest:'10000',funding:state.funding});
 await page.route('**/info',async r=>{const q=r.request().postDataJSON();let data;
 if(q.type==='meta')data=meta;
 else if(q.type==='spotMeta')data={tokens:[{name:'USDC',index:0,szDecimals:2},{name:'HYPE',index:1,szDecimals:2}],universe:[{name:'@0',tokens:[1,0],index:0}]};
 else if(['metaAndAssetCtxs','spotMetaAndAssetCtxs'].includes(q.type)){if(state.unavailable)return r.fulfill({status:503,body:'Unavailable'});data=[meta,[ctx(),ctx()]]}
 else if(q.type==='candleSnapshot')data=Array.from({length:70},(_,i)=>{const c=20+i/80+Math.sin(i/4)/5;return {t:Date.now()-(70-i)*60000,o:String(c-.05),h:String(c+.1),l:String(c-.15),c:String(c),v:String(30+i%12),s:q.req.coin,i:q.req.interval}});
 else if(q.type==='activeAssetData')data={coin:q.coin,user:A,leverage:{type:state.margin,value:state.leverage},maxTradeSzs:['100','100'],availableToTrade:['1000','1000'],markPx:'21'};
 else if(q.type==='clearinghouseState')data={marginSummary:{accountValue:'1000'},withdrawable:'800',assetPositions:[{position:{coin:'ETH',szi:state.position,entryPx:'19',liquidationPx:'10',marginUsed:'20',unrealizedPnl:'4',leverage:{type:state.margin,value:state.leverage},cumFunding:{sinceOpen:'-0.001'}}}]};
 else if(q.type==='spotClearinghouseState')data={balances:[{coin:'USDC',total:'500',hold:'50'}]};
 else if(q.type==='frontendOpenOrders'||q.type==='openOrders')data=state.orders;
 else if(q.type==='userFills')data=[{time:Date.now(),coin:'ETH',dir:'Open Long',side:'B',px:'20',sz:'2',fee:'0.02',feeToken:'USDC',closedPnl:'0'}];
 else if(q.type==='userFunding')data=[{time:Date.now(),delta:{coin:'ETH',fundingRate:'.0001',szi:'2',usdc:'-0.004'}}];
 else if(q.type==='orderStatus'){const o=posted.find(x=>x.action.type==='order')?.action.orders[0];data={status:'order',order:{order:{coin:'ETH',cloid:o?.c},status:'filled'}}}
 else data=[];await r.fulfill({json:data});
 });
 await page.route('**/exchange',r=>{const data=r.request().postDataJSON();posted.push(data);if(state.unknown)return r.abort();const a=data.action;if(a.type==='updateLeverage'){state.leverage=a.leverage;state.margin=a.isCross?'cross':'isolated';return r.fulfill({json:{status:'ok',response:{type:'default'}}})}if(a.type==='cancel')return r.fulfill({json:{status:'ok',response:{type:'cancel',data:{statuses:['success']}}}});return r.fulfill({json:{status:'ok',response:{type:'order',data:{statuses:[{resting:{oid:77}}]}}}})});
 await page.addInitScript(()=>{window.term={chain:'0x66eee',stale:false,rejected:false,requests:[]};window.ethereum={on(){},removeListener(){},async request(q){term.requests.push(q);if(['eth_accounts','eth_requestAccounts'].includes(q.method))return ['0x1111111111111111111111111111111111111111'];if(q.method==='eth_chainId')return term.chain;if(q.method==='wallet_switchEthereumChain')return null;if(q.method==='eth_signTypedData_v4'){if(term.rejected)throw {code:4001,message:'User rejected'};return '0x'+'11'.repeat(64)+'1b'}throw Error(q.method)}};
 window.WebSocket=class{constructor(){this.readyState=1;setTimeout(()=>this.onopen?.(),0)}send(text){const q=JSON.parse(text);if(q.subscription?.type==='l2Book'){this.timer=setInterval(()=>{if(!term.stale)this.onmessage?.({data:JSON.stringify({channel:'l2Book',data:{coin:q.subscription.coin,time:Date.now(),levels:[[{px:'20',sz:'3'},{px:'19.9',sz:'5'}],[{px:'21',sz:'4'},{px:'21.1',sz:'8'}]]}})})},200)}}close(){clearInterval(this.timer);this.readyState=3}};
 });
 return {state,posted};
}
async function connect(page){await page.goto('/qorvexa-dex/#markets');await page.locator('#marketNetwork').selectOption('testnet');await page.locator('#tradeConnect').click();await expect(page.locator('#tradeReview')).toBeEnabled();await expect(page.locator('#tradeLeverageCurrent')).toContainText('5x');}
async function marketOrder(page,side='buy'){await page.locator('#tradeType').selectOption('Market');await page.locator('#tradeSide').selectOption(side);await page.locator('#tradeSize').fill('1');await page.locator('#tradeReview').click();await expect(page.locator('#tradeDialog')).toBeVisible();}
test('visible book, signed funding direction, clock, stats and price selection',async({page})=>{
 await fixture(page);await page.goto('/qorvexa-dex/#markets');await expect(page.locator('#marketFunding')).toHaveText('+0.0100%');await expect(page.locator('#marketFundingDirection')).toHaveText('Longs pay shorts');await expect(page.locator('#marketFundingCountdown')).toHaveText(/\d\d:\d\d/);await expect(page.locator('#marketBids button')).toHaveCount(2);await page.locator('#marketAsks button').last().click();await expect(page.locator('#tradePrice')).toHaveValue('21');await expect(page.locator('#marketMark')).toHaveText('21');await page.screenshot({path:'test-results/wallet-terminal-desktop.jpg',type:'jpeg',quality:70,fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/wallet-terminal-mobile.jpg',type:'jpeg',quality:70,fullPage:true});
});
test('negative funding is shorts-pay-longs and unavailable never becomes zero',async({page})=>{const {state}=await fixture(page);state.funding='-0.0002';await page.goto('/qorvexa-dex/#markets');await expect(page.locator('#marketFunding')).toHaveText('-0.0200%');await expect(page.locator('#marketFundingDirection')).toHaveText('Shorts pay longs');state.unavailable=true;await page.locator('#marketRefresh').click();await expect(page.locator('#marketFunding')).toHaveText('Unavailable');});
for(const side of ['buy','sell'])test(`market ${side} signs one price-bounded IOC`,async({page})=>{const {posted}=await fixture(page);await connect(page);await marketOrder(page,side);expect(posted).toHaveLength(0);await page.locator('#tradeSubmit').click();await expect(page.locator('#tradeStatus')).toContainText('Order placed');expect(posted).toHaveLength(1);expect(posted[0].action.orders[0]).toMatchObject({a:0,b:side==='buy',p:side==='buy'?'21.1':'19.9',s:'1',t:{limit:{tif:'Ioc'}}});});
test('leverage applies only after review and uses real market bounds',async({page})=>{const {posted}=await fixture(page);await connect(page);await page.locator('#tradeLeverage').fill('21');await page.locator('#tradeLeverageReview').click();await expect(page.locator('#tradeStatus')).toContainText('1 to 20x');expect(posted).toHaveLength(0);await page.locator('#tradeLeverage').fill('10');await page.locator('#tradeMarginMode').selectOption('isolated');await page.locator('#tradeLeverageReview').click();await expect(page.locator('#tradeSummary')).toContainText('New: Isolated · 10x');expect(posted).toHaveLength(0);await page.locator('#tradeSubmit').click();await expect(page.locator('#tradeStatus')).toHaveText('Applied isolated 10x');expect(posted[0].action).toMatchObject({type:'updateLeverage',asset:0,leverage:10,isCross:false});});
test('leverage changing after order review prevents submission',async({page})=>{const {posted,state}=await fixture(page);await connect(page);await marketOrder(page);state.leverage=10;await page.locator('#tradeSubmit').click();await expect(page.locator('#tradeStatus')).toContainText('Leverage changed');expect(posted).toHaveLength(0);});
test('stop loss reduces only the existing position with an explicit trigger',async({page})=>{const {posted}=await fixture(page);await connect(page);await page.locator('#tradePositions').getByRole('button',{name:'SL',exact:true}).click();await page.locator('#tradeTrigger').fill('18');await page.locator('#tradeReview').click();await expect(page.locator('#tradeSummary')).toContainText('Trigger: 18');await page.locator('#tradeSubmit').click();await expect(page.locator('#tradeStatus')).toContainText('Order placed');expect(posted[0].action.orders[0]).toMatchObject({b:false,s:'2',r:true,t:{trigger:{isMarket:true,triggerPx:'18',tpsl:'sl'}}});});
test('reduce-only size cannot exceed the actual position',async({page})=>{const {posted}=await fixture(page);await connect(page);await page.locator('#tradePositions').getByRole('button',{name:'Close',exact:true}).click();await page.locator('#tradeSize').fill('3');await page.locator('#tradeReview').click();await expect(page.locator('#tradeStatus')).toContainText('existing position');expect(posted).toHaveLength(0);});
test('an ambiguous order remains locked until its cloid is verified',async({page})=>{const {posted,state}=await fixture(page);await connect(page);state.unknown=true;await marketOrder(page);await page.locator('#tradeSubmit').click();await expect(page.locator('#tradeStatus')).toContainText('unresolved');await expect(page.locator('#tradeReview')).toBeDisabled();expect(posted).toHaveLength(1);state.unknown=false;await page.locator('#tradeReconcile').click();await expect(page.locator('#tradeStatus')).toContainText('Verified order status: filled');await expect(page.locator('#tradeReview')).toBeEnabled();expect(posted).toHaveLength(1);});
test('wallet rejection is not automatically retried or locked as accepted',async({page})=>{const {posted}=await fixture(page);await connect(page);await marketOrder(page);await page.evaluate(()=>term.rejected=true);await page.locator('#tradeSubmit').click();await expect(page.locator('#tradeStatus')).toContainText(/reject/i);expect(posted).toHaveLength(0);await expect(page.locator('#tradeReconcile')).toBeHidden();});
test('funding history, fills and spot restrictions are visible',async({page})=>{await fixture(page);await connect(page);await page.locator('[data-account-tab="funding"]').click();await expect(page.locator('#tradeFundingHistory')).toContainText('-0.004');await page.locator('[data-account-tab="fills"]').click();await expect(page.locator('#tradeFills')).toContainText('Open Long');await page.locator('#marketType').selectOption('spot');await expect(page.locator('#tradeLeveragePanel')).toBeHidden();await expect(page.locator('#marketFundingCard')).toBeHidden();await expect(page.locator('#tradeReduce')).toBeDisabled();});
